---
application:
  name: "storage-api"
  project: "storage-api"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "doan_cnpm"
  version: "8.0"
routers:
- name: "main-storage-api"
  routes:
  - application_name: "storage-api"
    paths:
    - "/*"
